feat(semver): add ignore merge flag
jscutlery/semver pull request #583
Opened 2022-08-25 10:29 UTC by cakeinpanic

Provided a solution to fix this issue
https://github.com/jscutlery/semver/issues/541

2022-08-29 09:13 UTC, cakeinpanic commented
@edbzn WDYT?

2022-09-01 07:35 UTC, edbzn requested changes
In my opinion, semver should ignore merge commits and more generally any commits that do not follow the semver spec but it is not necessary to add a new option to the executor for this, it is probably a breaking change but anyway, it should be the normal behavior.

2022-09-01 07:37 UTC, cakeinpanic commented on packages/semver/src/executors/version/utils/git.ts
> +      'full-history': true,
I added explanation here https://github.com/conventional-changelog/conventional-changelog/issues/924

2022-09-01 07:37 UTC, cakeinpanic commented on packages/semver/src/executors/version/schema.json
> +    },
but what if someone adds significant information into merge commit titles?

2022-09-01 07:37 UTC, cakeinpanic commented on packages/semver/src/executors/version/index.e2e.spec.ts
> +jest.setTimeout(1000000)
it is, I just forgot to remove it after debugging in webstorm :)

2022-09-01 07:40 UTC, cakeinpanic commented
@edbzn I'd be glad to ignore merge commits by default, but have some doubts about people probably relying on them...

2022-09-04 11:07 UTC, cakeinpanic commented on packages/semver/src/executors/version/schema.json
> +    },
I gave it a thought and decided to make this behavior built-in as you suggested

2022-09-05 08:09 UTC, edbzn approved these changes

2022-09-05 08:10 UTC, merged